---
title: 'Reproducible Research: Peer Assessment 1'
output:
  html_document:
    keep_md: yes
  pdf_document: default
---


## Loading and preprocessing the data
```{r, LoadData}
strUrl <-"https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip"
strFile <-"activity.zip"
if (!file.exists(strFile))
{
     download.file(url = strUrl, destfile = "activity.zip", method = "curl", mode = "wb")  
}
lstOfFiles <-unzip(zipfile = strFile)
#
df <-read.csv(file = lstOfFiles[1], colClasses = c("integer","character","integer"))
#
str(df)
#
df$interval.ori <-df$interval
df$interval <-sprintf(fmt = "%04d", df$interval)
#
df$date.ori <-df$date
df$date <-as.Date(df$date)
#
df$dayofweek <-weekdays(df$date)
#
df$daytype <-"weekday"
df[substr(df$dayofweek,1,1) == "S", "daytype"] <-"weekend"
df$daytype <-factor(df$daytype, levels = c("weekday","weekend"))
#
str(df)
```

## What is mean total number of steps taken per day?
```{r, TotalStepsPerDay}
# 1. Calculae the total number of steps taken per day
TotalStepsPerDay <-tapply(X = df$steps, INDEX = df$date, FUN = sum, na.rm = TRUE)
head(TotalStepsPerDay, n = 25)
# 2. Make a histogram of the total number of steps taken each day.
hist(x = TotalStepsPerDay, breaks = 60)
# 3. Calculae and report the mean and the median of the total number of steps taken per day.
(meanTotalStepsPerDay <-mean(TotalStepsPerDay))
(medianTotalStepsPerDay <-median(TotalStepsPerDay))
```

## What is the average daily activity pattern?
```{r, AvgStepsPerInterval}
AvgStepsPerInterval <-tapply(X = df$steps, INDEX = df$interval, FUN = mean, na.rm = TRUE)
head(AvgStepsPerInterval, n = 25)
# 1. Make a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis)
plot(names(AvgStepsPerInterval), AvgStepsPerInterval,type = "l", xlab = "5 Minute Intervals")
# 2. Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?
(maxAvgStepsPerInterval <-AvgStepsPerInterval[AvgStepsPerInterval == max(AvgStepsPerInterval)])
```

## Imputing missing values
```{r, ImputMissingValues}
# 1. Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NAs)
sum(!complete.cases(df))
sum(is.na(df$steps))
# 2. Devise a strategy for filling in all of the missing values in the dataset.
# create data frame "df_cc" of complete case
df_cc <-df[complete.cases(df),]
# create matrix of avg steps per interval (row name) by day of week (column name)
mxAvgStepsPerIntervalByDow <-tapply(X = df_cc$steps, INDEX = list(df_cc$interval,df_cc$dayofweek), mean, na.rm = TRUE)
# 3. Create a new dataset that is equal to the original dataset but with missing data filled in.
df_narpl <-df
# make copy of original steps variable
df_narpl$steps.ori <-df_narpl$steps
# loop through data frame "df_narpl" and replace NA steps with avg steps from replacement matix
for (i in 1:nrow(df_narpl))
{
     isteps <-df_narpl[i,"steps"]
     iinterval <-df_narpl[i,"interval"]
     idayofweek <-df_narpl[i,"dayofweek"]
     # if steps is missing, replace with avg from dfcmatrix
     if(is.na(isteps))
     {
          df_narpl[i,"steps"] <-mxAvgStepsPerIntervalByDow[iinterval,idayofweek]
     }
}
# 4. Make a histogram of the total number of steps taken each day and calculate the mean and median total number of steps taken per day.
TotalStepsPerDay_narpl <-tapply(X = df_narpl$steps, INDEX = df_narpl$date, FUN = sum, na.rm = TRUE)
# histogram
hist(x = TotalStepsPerDay_narpl, breaks = 60)
# mean and median
meanTotalStepsPerDay_narpl <-mean(TotalStepsPerDay_narpl)
medianTotalStepsPerDay_narpl <-median(TotalStepsPerDay_narpl)
# compare with mean where incomplete records (NAs) were removed
(meanDiff <-meanTotalStepsPerDay_narpl - meanTotalStepsPerDay)
# compare with median where incomplete records (NAs) were removed
(medianDiff <-medianTotalStepsPerDay_narpl - medianTotalStepsPerDay)
```

## Are there differences in activity patterns between weekdays and weekends?
```{r, WeekdayWeekendDifference}
df_narpl$dayofweek <-weekdays(df_narpl$date)
# 1. Create a new factor variable in the dataset with two levels - "weekday" and "weekend" indicating whether a given date is a weekday or a weekend day.
df_narpl$daytype <-"weekday"
df_narpl[substr(df_narpl$dayofweek,1,1) == "S", "daytype"] <-"weekend"
df_narpl$daytype <-factor(df_narpl$daytype)
# 2. Make a panel plot containg a time serie plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all weekdays or weekend days (y-axis)
# create a matrix of average number of steps taken per interval per daytype (weekday & weekend)
mxAvgStepsPerIntervalByDayType <-tapply(X = df_narpl$steps, INDEX = list(df_narpl$interval, df_narpl$daytype), FUN = mean, na.rm = TRUE)
str(mxAvgStepsPerIntervalByDayType)
# reshape the matrix to a data frame with 3 columns : interval, day type and avg steps per interval
require(reshape2)
df_mlt <-melt(data = mxAvgStepsPerIntervalByDayType, measure.vars = c("weekday","weekend"), id.vars = c("interval"))
# update column/variable names
names(df_mlt) <-c("timeInterval","dayType","avgSteps")
str(df_mlt)
# create panel plots of avg steps by interal for each day type (weekday & weekend)
require("lattice")
xyplot(avgSteps ~ timeInterval | dayType, data = df_mlt, type = "l", layout = c(1,2), xlab = "5 Minute Intervals", ylab = "Avg Steps Per 5 Minute Interval" )
```

